# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: ${env:SERVICE_NAME, 'blog'}
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '4'

provider:
  name: aws
  runtime: ${env:RUNTIME, 'nodejs22.x'}
  endpointType: ${env:ENDPOINT_TYPE, 'regional'}
  profile: ${env:APP_NAME, 'taleofddh'}

  # you can overwrite defaults here
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  environment:
    ENVIRONMENT: ${opt:stage, self:provider.stage}
    REGION: ${opt:region, 'eu-west-1'}
    APP_NAME: ${env:APP_NAME, 'taleofddh'}
    SERVICE_NAME: ${env:SERVICE_NAME, 'blog'}
    S3_BUCKET: ${env:S3_BUCKET, 'taleofddh-blogs'}
    S3_MEDIA_BUCKET: ${env:S3_MEDIA_BUCKET, 'taleofddh-media'}
    SIGNER_PRIVATE_KEY: ${env:SIGNER_PRIVATE_KEY, 'SIGNER_PRIVATE_KEY'}
    CLOUDFRONT_PUBLIC_KEY_ID: ${env:CLOUDFRONT_PUBLIC_KEY_ID, 'K1XBUPGFMXTF6Q'}
    MEDIA_PROTECTED_HOST: ${env:MEDIA_PROTECTED_HOST, 'https://media-protected.taleofddh.com'}

  apiGateway:
    shouldStartNameWithService: true

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - lambda:InvokeFunction
        - secretsmanager:GetSecretValue
        - kms:Encrypt
        - kms:Decrypt
        - kms:ReEncrypt*
        - kms:GenerateDataKey*
        - kms:DescribeKey
      Resource: "*"
    - Effect: "Allow"
      Action:
        - s3:ListBucket
      Resource:
        - arn:aws:s3:::${env:S3_BUCKET, 'taleofddh-blogs'}
        - arn:aws:s3:::${env:S3_MEDIA_BUCKET, 'taleofddh-media'}
    - Effect: "Allow"
      Action:
        - s3:GetObject
      Resource:
        - arn:aws:s3:::${env:S3_BUCKET, 'taleofddh-blogs'}/*
        - arn:aws:s3:::${env:S3_MEDIA_BUCKET, 'taleofddh-media'}/*
    - Effect: "Allow"
      Action:
        - dynamodb:BatchGetItem
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:BatchWriteItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: arn:aws:dynamodb:*:*:table/${self:provider.stage}.${env:APP_NAME, 'taleofddh'}.${self:service}.*

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  individually: true

functions:
  findBlogList:
    handler: handler.findBlogList
    events:
      - http:
          path: blogList
          method: get
          cors: true
    environment:
      TABLE_NAME: "blog"

  findCategorizedBlogList:
    handler: handler.findCategorizedBlogList
    events:
      - http:
          path: blogListCategorized
          method: post
          cors: true
    environment:
      TABLE_NAME: "blog"

  updateBlogViewCount:
    handler: handler.updateBlogViewCount
    events:
      - http:
          path: blogViewCount
          method: put
          cors: true
    environment:
      TABLE_NAME: "blog"

  findBlogArticleList:
    handler: handler.findBlogArticleList
    events:
      - http:
          path: blogArticleList
          method: post
          cors: true
    environment:
      TABLE_NAME: "article"

  findArticleList:
    handler: handler.findArticleList
    events:
      - http:
          path: articleList
          method: post
          cors: true
    environment:
      TABLE_NAME: "article"

  findArticleCommentList:
    handler: handler.findArticleCommentList
    events:
      - http:
          path: articleCommentList
          method: post
          cors: true
    environment:
      TABLE_NAME: "articleComment"

  addArticleComment:
    handler: handler.addArticleComment
    events:
      - http:
          path: articleComment
          method: post
          cors: true
    environment:
      TABLE_NAME: "articleComment"

  getArticleDocument:
    handler: handler.getArticleDocument
    events:
      - http:
          path: articleDocument
          method: post
          cors: true
          response:
            contentHandling: CONVERT_TO_BINARY
    environment:
      S3_BUCKET: ${env:S3_BUCKET, 'taleofddh-blogs'}

  findHistoricalBlogCategories:
    handler: handler.findHistoricalBlogCategories
    events:
      - http:
          path: blogHistoricalCategories
          method: get
          cors: true
    environment:
      TABLE_NAME: "blog"

  findBlogCategories:
    handler: handler.findBlogCategories
    events:
      - http:
          path: blogCategories
          method: get
          cors: true
    environment:
      TABLE_NAME: "blog"

  findHistoricalBlogNames:
    handler: handler.findHistoricalBlogNames
    events:
      - http:
          path: blogHistoricalNames/{category}
          method: get
          cors: true
          request:
            parameters:
              paths:
                category: true
    environment:
      TABLE_NAME: "blog"

  findBlogCategoryNames:
    handler: handler.findBlogCategoryNames
    events:
      - http:
          path: blogCategoryNames
          method: get
          cors: true
    environment:
      TABLE_NAME: "blog"

  findBlog:
    handler: handler.findBlog
    events:
      - http:
          path: blog/{category}/{name}
          method: get
          cors: true
          request:
            parameters:
              paths:
                category: true
                name: true
    environment:
      TABLE_NAME: "blog"

# you can add CloudFormation resource templates here
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"

plugins:
  - serverless-domain-manager
  - serverless-offline

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: ${env:API_DOMAIN, 'api.taleofddh.com'}
    dev: ${self:custom.stage}-${env:API_DOMAIN, 'api.taleofddh.com'}
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: ${env:BASE_PATH, 'blog'}
    stage: ${self:custom.stage}
    certificateName: ${env:CERTIFICATE_NAME, '*.taleofddh.com'}
    hostedZoneId: ${env:HOSTED_ZONE_ID, 'Z044305914KLOWN7PAF5E'}
    createRoute53Record: true
    endpointType: ${env:ENDPOINT_TYPE, 'regional'}
    securityPolicy: ${env:SECURITY_POLICY, 'tls_1_2'}
    apiType: ${env:API_TYPE, 'rest'}
